# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View



default:
  http_metas:
    content-type: text/html

  metas:
    title:        GDA - Gestor de Dados AcadÃªmicos
    #description:  symfony project
    #keywords:     symfony, project
    language:     pt_BR
    #robots:       index, follow

  stylesheets:    [main.css,style.css]

  javascripts:    []

  has_layout:     true
  layout:         layout